# ---------------------------------------------------------
# PostgreSQL database connection
#
# Spring uses these settings to connect to the paymentdb
# PostgreSQL database running on this computer.
# ---------------------------------------------------------

spring.datasource.url=jdbc:postgresql://localhost:5432/paymentdb
spring.datasource.username=postgres
spring.datasource.password=Maduro17!

# ---------------------------------------------------------
# JPA / Hibernate configuration
#
# update:
# Hibernate creates or updates tables based on our entities.
#
# show-sql:
# Prints generated SQL in the IntelliJ console so we can see
# what Hibernate is sending to PostgreSQL.
# ---------------------------------------------------------

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true